export const projects = [
    {
        title: 'Malú Premium',
        description: 'Malú es la marca premium de fajas modeladoras colombianas. Este e-commerce fue desarrollado con Next.js, enfocado en ofrecer un diseño exclusivo y animaciones fluidas. Incluye pasarela de pago, catálogo dinámico de productos, optimización SEO y experiencia de usuario de alta calidad adaptada a cualquier dispositivo móvil o de escritorio.',
        image: '/projects/malupremium.png?height=250&width=400',
        tags: ['Next.js', 'React', 'TailwindCSS', 'Framer Motion', 'SEO'],
        category: 'Full Stack',
        link: 'https://malupremium.com/',
        github: '#',
    },
    {
        title: 'DJ Zesko',
        description: 'Sitio web oficial y portafolio interactivo para DJ Zesko, enfocado en la música electrónica. Desarrollado con Next.js y estilizado con Tailwind CSS, este sitio incluye un reproductor de audio integrado, animaciones avanzadas, agenda de shows en vivo y una sección de reservas, ofreciendo una experiencia inmersiva y muy visual (modo oscuro premium).',
        image: '/projects/djzesko.png?height=250&width=400',
        tags: ['Next.js', 'React', 'TailwindCSS', 'Framer Motion', 'UI/UX'],
        category: 'Frontend',
        link: 'https://djzesko.com/',
        github: '#',
    },
    {
        title: 'Inmobiliaria Cyan',
        description: 'Aplicación web moderna para la búsqueda y visualización de bienes raíces. Permite explorar un catálogo de propiedades con filtros dinámicos, imágenes de alta calidad y detalles específicos de cada inmueble. Desarrollada con React y Vite, enfocada en un rendimiento ultrarrápido y una interfaz muy limpia.',
        image: '/projects/inmobiliaria.png?height=250&width=400',
        tags: ['React', 'Vite', 'TailwindCSS', 'React Router'],
        category: 'Frontend',
        link: 'https://inmobiliaria-cyan.vercel.app/',
        github: '#',
    },
    {
        title: 'Ecommerce Clara',
        description: 'Plataforma de comercio electrónico rápida e intuitiva, construida con React y Vite. Incluye funcionalidades completas de tienda como listado de productos, carrito de compras dinámico y un diseño totalmente adaptable (Responsive Design). Todo gestionado con un manejo de estado global eficiente.',
        image: '/projects/ecommerce-clara.png?height=250&width=400',
        tags: ['React', 'Vite', 'TailwindCSS', 'Zustand', 'React Router DOM'],
        category: 'Frontend',
        link: 'https://ecommerce-clara.vercel.app/',
        github: '#',
    },
    {
        title: 'Floristería Web',
        description: 'Sitio web elegante y minimalista diseñado para una floristería. Cuenta con un catálogo visual de arreglos florales y opciones de personalización para el cliente. Construida utilizando React y Vite, su interfaz destaca por colores suaves y una experiencia de navegación agradable, pensada en la conversión del usuario.',
        image: '/projects/floristeria.png?height=250&width=400',
        tags: ['React', 'Vite', 'TailwindCSS', 'Framer Motion'],
        category: 'Frontend',
        link: 'https://floristeriaweb.vercel.app/',
        github: '#',
    },
    {
        title: 'Barber Shop Website',
        description: 'Es una web para agendar citas de forma rápida y sencilla. Los usuarios pueden registrarse, reservar su servicio con el barbero de su elección y llevar el control de sus citas. Ideal para organizar agendas y ofrecer una atención profesional.',
        image: '/projects/barber-frontend.png?height=250&width=400',
        tags: [
            'React',
            'TypeScript',
            'Zustand',
            'Formik',
            'Yup',
            'TailwindCSS',
            'Axios',
            'React-router-dom',
            'Google',
        ],
        category: 'Full Stack',
        link: 'https://frontend-web-barber.vercel.app/',
        github: 'https://github.com/Alexisrk310/frontend-web-barber',
    },
    {
        title: 'Barber Shop Backend',
        description: 'El backend está desarrollado con Node.js, Express y Prisma, ofreciendo una API REST segura para gestionar usuarios, citas y servicios. Soporta registro e inicio de sesión con JWT, validación de horarios, control de roles (cliente/admin) ',
        image: '/projects/barber-frontend.png?height=250&width=400',
        tags: [
            'Node.js',
            'Prisma',
            'PostgreSQL',
            'Express',
            'JWT',
            'Bcrypt',
            'Cors',
            'Google-Auth',
            'Dayjs',
        ],
        category: 'Backend',
        link: '#',
        github: 'https://github.com/Alexisrk310/webbarber-backend',
    },
    {
        title: 'Translogistica SLA',
        description: 'Página web informativa para una empresa de transporte y logística nacional, diseñada para presentar sus servicios, mostrar quiénes son y facilitar el contacto con los clientes. Cuenta con un diseño moderno y adaptable, pensado para brindar confianza y claridad.',
        image: '/projects/translogisticasla.png?height=250&width=400',
        tags: ['Next.js', 'Emailjs', 'React-hook-form', 'Sitemap', 'TailwindCSS'],
        category: 'Frontend',
        link: 'https://translogisticasla.com/',
        github: 'https://github.com/Alexisrk310/SLATRANSLOGISTICA',
    },
    {
        title: 'Rafa Express',
        description: 'Página web para un restaurante con menú interactivo y pasarela de pago integrada, que permite a los usuarios comprar su comida favorita en línea y recibirla directamente en la puerta de su casa. Diseñada para una experiencia rápida, intuitiva y cómoda.',
        image: '/projects/rafaexpress.png?height=250&width=400',
        tags: ['React', 'TailwindCSS', 'React-hook-form', 'ePayco'],
        category: 'Frontend',
        link: 'https://landing-page-template-opal.vercel.app/',
        github: 'https://github.com/Alexisrk310/landing-page-template',
    },
    {
        title: 'ThunderXis',
        description: 'Página web para un restaurante con menú interactivo y pasarela de pago integrada, que permite a los usuarios realizar pedidos en línea de forma rápida y segura. Incluye una experiencia de usuario intuitiva, diseño responsive, gestión de productos y flujo de compra optimizado para recibir el producto directamente en la puerta de su casa.',
        image: '/projects/thunderxis.png?height=250&width=400',
        tags: [
            'Next.js',
            'React',
            'TypeScript',
            'Tailwind CSS',
            'Radix UI',
            'Lucide Icons',
            'CSS-in-JS',
            'Responsive Design',
            'UI/UX',
            'React Hook Form',
            'Zod',
            'Form Validation',
            'Zustand',
            'Framer Motion',
            'Sonner (Toasts)',
            'Canvas Confetti',
            'Supabase',
            'Supabase Auth',
            'Supabase SSR',
            'Recharts',
            'Date-fns',
            'jsPDF',
            'jsPDF AutoTable',
            'ExcelJS',
            'FileSaver',
            'MercadoPago',
            'Resend',
            'Clsx',
            'Tailwind Merge',
            'Class Variance Authority',
            'Server Components',
            'Client Components',
            'API Routes',
            'SSR',
            'SEO',
            'Clean Architecture',
            'Reusable Components'
        ],
        category: 'Full Stack',
        link: 'https://thunderxis.store',
        github: 'https://github.com/Alexisrk310/thunderxis',
    },
    {
        title: 'Foodies',
        description: 'Aplicación web full stack para pedidos de comida en línea, desarrollada con Next.js y React. Incluye gestión de productos, autenticación con Supabase, formularios validados, generación de reportes en PDF y Excel, animaciones, gráficos y pasarela de pago integrada con MercadoPago. Diseño responsive, experiencia de usuario optimizada y arquitectura limpia con componentes reutilizables.',
        image: '/projects/foodies.png?height=250&width=400',
        tags: [
            'Next.js',
            'React',
            'TypeScript',
            'Tailwind CSS',
            'Radix UI',
            'Lucide React',
            'Responsive Design',
            'UI/UX',
            'React Hook Form',
            'Zod',
            'Form Validation',
            'Zustand',
            'Framer Motion',
            'Sonner (Toasts)',
            'Canvas Confetti',
            'Supabase',
            'Supabase Auth',
            'Supabase SSR',
            'Recharts',
            'Date-fns',
            'jsPDF',
            'jsPDF AutoTable',
            'ExcelJS',
            'FileSaver',
            'MercadoPago',
            'Resend',
            'Clsx',
            'Tailwind Merge',
            'Class Variance Authority',
            'Server Components',
            'Client Components',
            'API Routes',
            'SSR',
            'SEO',
            'Clean Architecture',
            'Reusable Components'
        ],
        category: 'Full Stack',
        link: 'https://shop-food-seven.vercel.app/',
        github: 'https://github.com/Alexisrk310/shop-food'
    },
    {
        title: 'Menu Restaurant',
        description: 'Aplicación web para restaurantes que permite mostrar un menú digital interactivo con navegación por rutas públicas y privadas. Incluye generación de códigos QR para acceso rápido al menú, animaciones fluidas, diseño responsive y una experiencia moderna optimizada para dispositivos móviles. Construida con React y Vite, utilizando Supabase como backend y una arquitectura limpia con componentes reutilizables.',
        image: '/projects/menu-restaurant.png?height=250&width=400',
        tags: [
            'React',
            'TypeScript',
            'Vite',
            'Tailwind CSS',
            'React Router DOM',
            'Supabase',
            'Framer Motion',
            'Lucide React',
            'QR Code',
            'QR Menu',
            'Responsive Design',
            'UI/UX',
            'Clsx',
            'Tailwind Merge',
            'Component-Based Architecture',
            'Reusable Components'
        ],
        category: 'Frontend',
        link: 'https://menu-restaurant-xi-ten.vercel.app/',
        github: 'https://github.com/Alexisrk310/menu-restaurant'
    }
];
