export const projects = [
	{
		title: 'Barber Shop Website',
		description:
			'Es una web para agendar citas de forma rápida y sencilla. Los usuarios pueden registrarse, reservar su servicio con el barbero de su elección y llevar el control de sus citas. Ideal para organizar agendas y ofrecer una atención profesional.',
		image: '/projects/barber-frontend.png?height=250&width=400',
		tags: [
			'React',
			'TypeScript',
			'Zustand',
			'Formik',
			'Yup',
			'TailwindCSS',
			'Axios',
			'React-router-dom',
			'Google',
		],
		category: 'Full Stack',
		link: 'https://frontend-web-barber.vercel.app/',
		github: 'https://github.com/Alexisrk310/frontend-web-barber',
	},
	{
		title: 'Barber Shop Backend',
		description:
			'El backend está desarrollado con Node.js, Express y Prisma, ofreciendo una API REST segura para gestionar usuarios, citas y servicios. Soporta registro e inicio de sesión con JWT, validación de horarios, control de roles (cliente/admin) ',
		image: '/projects/barber-frontend.png?height=250&width=400',
		tags: [
			'Node.js',
			'Prisma',
			'PostgreSQL',
			'Express',
			'JWT',
			'Bcrypt',
			'Cors',
			'Google-Auth',
			'Dayjs',
		],
		category: 'Backend',
		link: '#',
		github: 'https://github.com/Alexisrk310/webbarber-backend',
	},
	{
		title: 'Store',
		description:
			'Store es una aplicación web tipo ecommerce desarrollada con React, TailwindCSS, Zustand y React Router DOM. Ofrece una experiencia fluida e intuitiva, permitiendo a los usuarios explorar productos y filtrarlos fácilmente por categoría, talla y precio. Su diseño es moderno y adaptable a diferentes dispositivos.',
		image: '/projects/store.png?height=250&width=400',
		tags: ['React', 'Motion', 'TailwindCSS', 'Zustand', 'React-router-dom'],
		category: 'Frontend',
		link: 'https://store-qwer.vercel.app/',
		github: 'https://github.com/Alexisrk310/store',
	},
	{
		title: 'TransQ',
		description:
			'TransQ es una página web enfocada en servicios de envíos y logística, inspirada en plataformas como DHL. Actualmente se encuentra en la etapa de diseño frontend, desarrollada con una interfaz moderna y adaptable, lista para integrar funcionalidades backend en futuras fases.',
		image: '/projects/transq.png?height=250&width=400',
		tags: ['Next.js', 'Framer Motion', 'Tailwind', 'Vercel'],
		category: 'Frontend',
		link: 'https://company-green-eight.vercel.app/',
		github: '#',
	},
	{
		title: 'Translogistica SLA',
		description:
			'Página web informativa para una empresa de transporte y logística nacional, diseñada para presentar sus servicios, mostrar quiénes son y facilitar el contacto con los clientes. Cuenta con un diseño moderno y adaptable, pensado para brindar confianza y claridad.',
		image: '/projects/translogisticasla.png?height=250&width=400',
		tags: ['Next.js', 'Emailjs', 'React-hook-form', 'Sitemap', 'TailwindCSS'],
		category: 'Frontend',
		link: 'https://translogisticasla.com/',
		github: 'https://github.com/Alexisrk310/SLATRANSLOGISTICA',
	},
	{
		title: 'Rafa Express',
		description:
			'Página web para un restaurante con menú interactivo y pasarela de pago integrada, que permite a los usuarios comprar su comida favorita en línea y recibirla directamente en la puerta de su casa. Diseñada para una experiencia rápida, intuitiva y cómoda.',
		image: '/projects/rafaexpress.png?height=250&width=400',
		tags: ['React', 'TailwindCSS', 'React-hook-form', 'ePayco'],
		category: 'Frontend',
		link: 'https://landing-page-template-opal.vercel.app/',
		github: 'https://github.com/Alexisrk310/landing-page-template',
	},
	{
		title: 'ThunderXis',
		description:
			'Página web para un restaurante con menú interactivo y pasarela de pago integrada, que permite a los usuarios realizar pedidos en línea de forma rápida y segura. Incluye una experiencia de usuario intuitiva, diseño responsive, gestión de productos y flujo de compra optimizado para recibir el producto directamente en la puerta de su casa.',
		image: '/projects/thunderxis.png?height=250&width=400',
		tags: [
			'Next.js',
			'React',
			'TypeScript',
			'Tailwind CSS',
			'Radix UI',
			'Lucide Icons',
			'CSS-in-JS',
			'Responsive Design',
			'UI/UX',
			'React Hook Form',
			'Zod',
			'Form Validation',
			'Zustand',
			'Framer Motion',
			'Sonner (Toasts)',
			'Canvas Confetti',
			'Supabase',
			'Supabase Auth',
			'Supabase SSR',
			'Recharts',
			'Date-fns',
			'jsPDF',
			'jsPDF AutoTable',
			'ExcelJS',
			'FileSaver',
			'MercadoPago',
			'Resend',
			'Clsx',
			'Tailwind Merge',
			'Class Variance Authority',
			'Server Components',
			'Client Components',
			'API Routes',
			'SSR',
			'SEO',
			'Clean Architecture',
			'Reusable Components'
		]
		,
		category: 'Full Stack',
		link: 'https://thunderxis.store',
		github: 'https://github.com/Alexisrk310/thunderxis',
	},
	{
		title: 'Foodies',
		description:
			'Aplicación web full stack para pedidos de comida en línea, desarrollada con Next.js y React. Incluye gestión de productos, autenticación con Supabase, formularios validados, generación de reportes en PDF y Excel, animaciones, gráficos y pasarela de pago integrada con MercadoPago. Diseño responsive, experiencia de usuario optimizada y arquitectura limpia con componentes reutilizables.',
		image: '/projects/foodies.png?height=250&width=400',
		tags: [
			'Next.js',
			'React',
			'TypeScript',
			'Tailwind CSS',
			'Radix UI',
			'Lucide React',
			'Responsive Design',
			'UI/UX',
			'React Hook Form',
			'Zod',
			'Form Validation',
			'Zustand',
			'Framer Motion',
			'Sonner (Toasts)',
			'Canvas Confetti',
			'Supabase',
			'Supabase Auth',
			'Supabase SSR',
			'Recharts',
			'Date-fns',
			'jsPDF',
			'jsPDF AutoTable',
			'ExcelJS',
			'FileSaver',
			'MercadoPago',
			'Resend',
			'Clsx',
			'Tailwind Merge',
			'Class Variance Authority',
			'Server Components',
			'Client Components',
			'API Routes',
			'SSR',
			'SEO',
			'Clean Architecture',
			'Reusable Components'
		],
		category: 'Full Stack',
		link: 'https://shop-food-seven.vercel.app/',
		github: 'https://github.com/Alexisrk310/shop-food'
	},
	{
		title: 'Menu Restaurant',
		description:
			'Aplicación web para restaurantes que permite mostrar un menú digital interactivo con navegación por rutas públicas y privadas. Incluye generación de códigos QR para acceso rápido al menú, animaciones fluidas, diseño responsive y una experiencia moderna optimizada para dispositivos móviles. Construida con React y Vite, utilizando Supabase como backend y una arquitectura limpia con componentes reutilizables.',
		image: '/projects/menu-restaurant.png?height=250&width=400',
		tags: [
			'React',
			'TypeScript',
			'Vite',
			'Tailwind CSS',
			'React Router DOM',
			'Supabase',
			'Framer Motion',
			'Lucide React',
			'QR Code',
			'QR Menu',
			'Responsive Design',
			'UI/UX',
			'Clsx',
			'Tailwind Merge',
			'Component-Based Architecture',
			'Reusable Components'
		],
		category: 'Frontend',
		link: 'https://menu-restaurant-xi-ten.vercel.app/',
		github: 'https://github.com/Alexisrk310/menu-restaurant'
	}


];
