import { Code, Code2, Globe, Palette, Smartphone, Terminal } from 'lucide-react';

export const technologies = [
	{
		category: 'Lenguajes',
		icon: Code2,
		skills: [
			'Java',
			'JavaScript',
			'TypeScript',
			'Python',
			'SQL',
		],
		color: 'from-sky-500 to-cyan-500',
	},
	{
		category: 'Frontend',
		icon: Code,
		skills: [
			'React',
			'Next.js',
			'Vite',
			'JavaScript',
			'TypeScript',
			'Tailwind CSS',
			'Bootstrap',
			'Astro',
			'Zustand',
			'Framer Motion',
			'Three.js',
			'React Three Fiber',
			'GSAP',
			'Redux',
			'React Router DOM',
			'React Hook Form',
			'Formik',
			'Yup',
			'Zod',
			'Axios',
			'Radix UI',
			'Lucide React',
			'Recharts',
			'Next Themes',
			'Responsive Design',
			'UI/UX',
			'SSR',
			'SEO',
		],
		color: 'from-cyan-500 to-sky-500',
	},
	{
		category: 'Backend',
		icon: Globe,
		skills: [
			'Node.js',
			'Express',
			'FastAPI',
			'PostgreSQL',
			'MySQL',
			'MongoDB',
			'Redis',
			'Celery',
			'Firebase',
			'Prisma',
			'SQLAlchemy',
			'JWT',
			'Bcrypt',
			'Cors',
			'Google Auth',
			'Supabase',
			'Supabase Auth',
			'Supabase SSR',
			'Socket.io',
			'API Routes',
			'Resend',
			'Stripe',
			'Mercado Pago',
		],
		color: 'from-sky-500 to-cyan-600',
	},
	{
		category: 'IA & Automatización',
		icon: Terminal,
		skills: [
			'Anthropic Claude',
			'OpenAI',
			'Groq',
			'Google Gemini',
			'LangChain',
			'WhatsApp Bot (Baileys)',
			'Playwright',
			'yt-dlp',
			'Faster-Whisper',
			'APScheduler',
		],
		color: 'from-cyan-400 to-sky-500',
	},
	{
		category: 'Mobil',
		icon: Smartphone,
		skills: [
			'React Native',
			'Expo',
			'iOS',
			'Android',
			'Android Studio',
		],
		color: 'from-sky-500 to-cyan-400',
	},
	{
		category: 'Herramientas',
		icon: Palette,
		skills: [
			'Git',
			'Github',
			'Figma',
			'Vercel',
			'Render',
			'Postman',
			'Google Cloud',
			'AWS S3',
			'Cloudinary',
			'ePayco',
			'Mercado Pago',
			'ESLint',
			'Prettier',
			'Vitest',
			'Playwright',
			'jsPDF',
			'ExcelJS',
			'QR Code',
		],
		color: 'from-sky-600 to-cyan-500',
	},
	{
		category: 'DevOps & Automation',
		icon: Terminal,
		skills: [
			'Docker',
			'Docker Compose',
			'GitHub Actions',
			'CI/CD',
			'Bash',
			'Python',
			'Husky',
			'Linux',
			'Nginx',
			'Cron Jobs',
		],
		color: 'from-cyan-500 to-teal-500',
	},
];
