import { Code, Code2, Globe, Palette, Smartphone } from 'lucide-react';

export const technologies = [
	{
		category: 'Lenguajes',
		icon: Code2,
		skills: ['Java', 'JavaScript', 'TypeScript', 'Python'],
		color: 'from-purple-500 to-pink-500',
	},
	{
		category: 'Frontend',
		icon: Code,
		skills: [
			'React',
			'Next.js',
			'JavaScript',
			'TypeScript',
			'Tailwind CSS',
			'Bootstrap',
			'Astro',
			'Zustand',
			'Framer Motion',
			'Redux',
			'React Router DOM',
			'Formik',
			'Yup',
			'Axios',
		],
		color: 'from-purple-500 to-indigo-500',
	},
	{
		category: 'Backend',
		icon: Globe,
		skills: [
			'Node.js',
			'PostgreSQL',
			'MySQL',
			'MongoDB',
			'Firebase',
			'Express',
			'Prisma',
			'JWT',
			'Bcrypt',
			'Cors',
			'Google Auth',
			'Supabase',
			'Resend',
		],
		color: 'from-indigo-500 to-purple-500',
	},
	{
		category: 'Mobil',
		icon: Smartphone,
		skills: ['React Native', 'Expo', 'iOS', 'Android', 'Android Studio'],
		color: 'from-purple-600 to-pink-500',
	},
	{
		category: 'Herramientas',
		icon: Palette,
		skills: [
			'Docker',
			'Git',
			'Github',
			'Figma',
			'Vercel',
			'Render',
			'Postman',
			'Google Cloud',
			'Stripe',
			'Cloudinary',
			'ePayco',
			'Mercado Pago',
		],
		color: 'from-indigo-600 to-purple-600',
	},
];
