'use client';
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { motion } from 'framer-motion';
import { Mail, Menu, X } from 'lucide-react';
import { Button } from './Button';
import { navLinks } from '@/constants/navLinks';
export function Navbar() {
    const [isOpen, setIsOpen] = useState(false);
    return (_jsxs(motion.nav, { initial: { opacity: 0, y: -50 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.6 }, className: "fixed top-0 w-full z-50 bg-white/80 backdrop-blur-md border-b border-purple-100 shadow-sm", children: [_jsxs("div", { className: "container mx-auto px-6 py-4 flex justify-between items-center", children: [_jsxs(motion.div, { whileHover: { scale: 1.05 }, className: "flex items-center space-x-2", children: [_jsx("div", { className: "w-10 h-10 bg-gradient-to-r from-purple-600 to-indigo-600 rounded-full flex items-center justify-center", children: _jsx("span", { className: "text-white font-bold text-lg", children: "A" }) }), _jsx("span", { className: "text-2xl font-bold text-gray-800", children: "Portafolio" })] }), _jsx("div", { className: "hidden md:flex space-x-8", children: navLinks.map((section) => (_jsx("a", { href: section.href, className: "text-gray-600 hover:text-purple-600 transition-colors font-medium capitalize", children: section.name }, section.name))) }), _jsx("div", { className: "hidden md:block", children: _jsxs(Button, { onClick: () => window.open('mailto:alexisrk310@gmail.com?subject=Estás disponible?', '_blank'), className: "bg-purple-600 hover:bg-purple-700 text-white px-6 py-2 rounded-full text-sm md:text-base", children: [_jsx(Mail, { className: "mr-2 h-4 w-4" }), "Contact Me"] }) }), _jsx("div", { className: "md:hidden", children: _jsx("button", { onClick: () => setIsOpen(!isOpen), className: "text-gray-700 hover:text-purple-600 focus:outline-none", children: isOpen ? _jsx(X, { className: "h-6 w-6" }) : _jsx(Menu, { className: "h-6 w-6" }) }) })] }), isOpen && (_jsxs("div", { className: "md:hidden bg-white px-6 py-4 space-y-4 border-t border-purple-100", children: [navLinks.map((section) => (_jsx("a", { href: section.href, className: "block text-gray-700 hover:text-purple-600 font-medium capitalize", onClick: () => setIsOpen(false), children: section.name }, section.name))), _jsxs(Button, { onClick: () => window.open('mailto:alexisrk310@gmail.com?subject=Estás disponible?', '_blank'), className: "w-full bg-purple-600 hover:bg-purple-700 text-white py-2 rounded-full flex justify-center items-center text-sm", children: [_jsx(Mail, { className: "mr-2 h-4 w-4" }), "Contact Me"] })] }))] }));
}
